### ISSUE TITLE
refactor: Adjust names and docs

### ISSUE THREAD

**Issue by duesee** [duesee/imap-next#105]
During our work on the "flows", the names got somehow out of hand. We will soon have all required "flows". Let's unify all names then.

* `SendCommandBlockedReason`
* `*Event`
* ...

**Comment by duesee** [comment]
Question @jakoschiko: Should we rename `ClientFlowEvent` and `ServerFlowEvent` to just `Event`? In the end, it will be not us using the library. And I expect it to be kinda rare that someone uses both client and server. What do you think?

**Comment by jakoschiko** [comment]
The current names are so long because the proxy was our first use case for `imap-flow` and it uses both client and server side. `server::Event` instead of `ServerFlowEvent` doesn't look that bad. However, the module name `server` has a high probability for name collisions. Maybe we should rename it, too, then it would be `server_flow::Event`.

I need more time to thing about this.

**Comment by jakoschiko** [comment]
@duesee: Should we close this?

**Comment by duesee** [comment]
Yes. We should take a focused look on `cargo doc` soon but I think this issue doesn't serve a purpose anymore.
