### ISSUE TITLE
Literal parsing has O(n²) complexity

### ISSUE THREAD

**Issue by jakoschiko** [duesee/imap-next#129]
If `ReceiveState` parses a message with n literals, then the complexity is O(n²). There is already a TODO in `receive.rs`:

```rust
// Try to parse the whole message from the start (including the new line).
// TODO: If the message is really long and we need multiple attempts to receive it, then this is O(n^2)
//       IMO this can be only fixed by using a generator-like decoder
match self.codec.decode(&self.read_buffer[..self.seen_bytes]) {
    Ok((remaining, message)) => {
        assert!(remaining.is_empty());
        Ok(Some(ReceiveEvent::DecodingSuccess(message.into_static())))
    }
    Err(error) => Ok(Some(ReceiveEvent::DecodingFailure(error.into_static()))),
}
```

Unfortunately I think there is no easy fix for that. The parser implemented in `imap-codec` would need to be stateful and remember the partially parsed message in order to solve the issue.

**Comment by jakoschiko** [comment]
Can we split the decoder in `imap-codec` into a fragment parser (that consumes bytes) and a message parser (that comsumes fragments)?

**Comment by duesee** [comment]
I'm open to any suggestion. The effort doing so depends on the concrete IMAP syntax, I guess. If we have deeply nested literals, we need to memoize a complex path up until this literal. Probably doing so multiple times. Sounds... not fun.

Also, some rules are much simpler than others. For example, we can already fix `GreetingCodec` (because it has no literals).

A dirty (and slightly incorrect) way of doing it would be to parse everything into `[Line, Literal, Line, Literal, ...]` first w/o doing any IMAP parsing at all. For example, we always just assume that when a line ends with `{...}`, it must be a literal. But I know of a case where this would lead to broken parsing of a valid message: `Text` is allowed to have `{` and `}`. So ...

```imap
A1 OK Your trace ID is {1234}
```

... would fail.

**Comment by jakoschiko** [comment]
The encoder in `imap-codec` already produces `[Line, Literal, Line, Literal, ...]`, so it would be symmetrical if the decoder consumes something similar.
